export const GAMES = {
  red: 'Red',
  blue: 'Blue',
  yellow: 'Yellow',
  gold: 'Gold',
  silver: 'Silver',
  crystal: 'Crystal',
  ruby: 'Ruby',
  sapphire: 'Sapphire',
  emerald: 'Emerald',
  firered: 'Fire Red',
  leafgreen: 'Leaf Green',
  diamond: 'Diamond',
  pearl: 'Pearl',
  platinum: 'Platinum',
  heartgold: 'Heart Gold',
  soulsilver: 'Soul Silver',
  black: 'Black',
  white: 'White',
  colosseum: 'Colosseum',
  xd: 'XD',
  'black-2': 'Black 2',
  'white-2': 'White 2',
  x: 'X',
  y: 'Y',
  'omega-ruby': 'Omega Ruby',
  'alpha-sapphire': 'Alpha Sapphire',
  sun: 'Sun',
  moon: 'Moon',
  'ultra-sun': 'Ultra Sun',
  'ultra-moon': 'Ultra Moon',
  'lets-go-pikachu': "Let's go Pikachu",
  'lets-go-eevee': "Let's go Eevee",
  sword: 'Sword',
  shield: 'Shield',
  'the-isle-of-armor': 'The Isle of Armor',
  'the-crown-tundra': 'The Crown Tundra',
  'brilliant-diamond': 'Brilliant Diamond',
  'shining-pearl': 'Shining Pearl',
  'legends-arceus': 'Legends: Arceus',
  scarlet: 'Scarlet',
  violet: 'Violet',
  'the-teal-mask': 'The Teal Mask',
  'the-indigo-disk': 'The Indigo Disk'
}
