const POKEDEX_ENDPOINT = 'https://pokeapi.co/api/v2/pokedex'

export const POKEDEXES = {
  // TODO: refactor -> national: {name: "National", url: `${POKEDEX_ENDPOINT}/1/`} ...
  national: `${POKEDEX_ENDPOINT}/1/`,
  kanto: `${POKEDEX_ENDPOINT}/2/`,
  'original-johto': `${POKEDEX_ENDPOINT}/3/`,
  hoenn: `${POKEDEX_ENDPOINT}/4/`,
  'original-sinnoh': `${POKEDEX_ENDPOINT}/5/`,
  'extended-sinnoh': `${POKEDEX_ENDPOINT}/6/`,
  'updated-johto': `${POKEDEX_ENDPOINT}/7/`,
  'original-unova': `${POKEDEX_ENDPOINT}/8/`,
  'updated-unova': `${POKEDEX_ENDPOINT}/9/`,
  'conquest-gallery': `${POKEDEX_ENDPOINT}/11/`,
  'kalos-central': `${POKEDEX_ENDPOINT}/12/`,
  'kalos-coastal': `${POKEDEX_ENDPOINT}/13/`,
  'kalos-mountain': `${POKEDEX_ENDPOINT}/14/`,
  'updated-hoenn': `${POKEDEX_ENDPOINT}/15/`,
  'original-alola': `${POKEDEX_ENDPOINT}/16/`,
  'original-melemele': `${POKEDEX_ENDPOINT}/17/`,
  "original-akala": `${POKEDEX_ENDPOINT}/18/`,
  "original-ulaula": `${POKEDEX_ENDPOINT}/19/`,
  "original-poni": `${POKEDEX_ENDPOINT}/20/`,
  "updated-alola": `${POKEDEX_ENDPOINT}/21/`,
  "updated-melemele": `${POKEDEX_ENDPOINT}/22/`,
  "updated-akala": `${POKEDEX_ENDPOINT}/23/`,
  "updated-ulaula": `${POKEDEX_ENDPOINT}/24/`,
  "updated-poni": `${POKEDEX_ENDPOINT}/25/`,
  "letsgo-kanto": `${POKEDEX_ENDPOINT}/26/`,
  galar: `${POKEDEX_ENDPOINT}/27/`,
  "isle-of-armor": `${POKEDEX_ENDPOINT}/28/`,
  "crown-tundra": `${POKEDEX_ENDPOINT}/29/`,
  hisui: `${POKEDEX_ENDPOINT}/30/`,
  paldea: `${POKEDEX_ENDPOINT}/31/`,
  kitakami: `${POKEDEX_ENDPOINT}/32/`,
  blueberry: `${POKEDEX_ENDPOINT}/33/`,
}
